services:
  - type: worker
    name: family-bot-pro
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: HUGGING_FACE_API_KEY
        sync: false
